### ISSUE TITLE
tflearn & TensorFlow 2.0

### ISSUE THREAD

**Issue by GabsReDeal** [anasselhoud/AI-MealBot#1]
Unfortunately, due to tflearn it is unable to run with an updated TensorFlow.

**Comment by anasselhoud** [comment]
Hello @GabsReDeal 

Can you specify which file you are talking about exactly? and what is the error?
Maybe I need to recheck the version of tf I was using while developing this.

**Comment by KhaledAdrani1997** [comment]
I got the same issue.

**Comment by khaledadrani** [comment]
I am working in Google colab and I got the same issue.
```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-944f8d16fbb3> in <module>()
      8 
      9 import numpy as np
---> 10 import tflearn
     11 from tensorflow.python.compiler.tensorrt import trt_convert as tf
     12 #import tensorflow as tf

2 frames
/usr/local/lib/python3.6/dist-packages/tflearn/variables.py in <module>()
      5 import tflearn
      6 
----> 7 from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
      8 from tensorflow.python.framework import ops
      9 from tensorflow.python.ops import variable_scope

ModuleNotFoundError: No module named 'tensorflow.contrib'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
I followed instruction in https://github.com/tensorflow/tensorflow/issues/31350 and still did not work:
```python
from tensorflow.python.compiler.tensorrt import trt_convert as trt
```
It seems that tflearn depends internally on tf.contrib. I read from the issue that tf.contrib doesn't exist in 2.0.

**Comment by anasselhoud** [comment]
Thank you @KhaledAdrani1997  for your comment. I will check that and see what can I do.

**Comment by anasselhoud** [comment]
@khaledadrani , Sorry for the late response. I was quite busy these last months.

You have to install the old version of TensorFlow. Please do:

`pip install tensorflow==1.13.2`

This version of TF has "contrib" module.
