### ISSUE TITLE
Newby unable to follow README instructions

### ISSUE THREAD

**Issue by pdorrestijn** [anasselhoud/AI-MealBot#2]
Hi as a Newby I tried to follow the instructions from the README but no success.
pip install -r requirements.txt failed on the python version:none (I have python 3.6.8 installed en pip 20.something, thus as a fallback I manually installed all imported modules using pip)
python main.py, intensions of the meal bot are not included in this repository... where to get it?

**Comment by anasselhoud** [comment]
Hello @pdorrestijn , sorry for the late answer.

Did you install all the required modules? If so, would you quote the exact error you get when trying to execute the main file? I think they may be some problems with Tensorflow version. But I have to check the error message to be sure about that.

Please check my tutorial on TDS: 
[How to build your own AI Chatbot on Discord?](https://towardsdatascience.com/how-to-build-your-own-ai-chatbot-on-discord-c6b3468189f4)
