### ISSUE TITLE
Can't find a version that satisfies the requirement

### ISSUE THREAD

**Issue by amadeusdotpng** [anasselhoud/AI-MealBot#3]
I follow the first step 
```
pip install -r requirements.txt
```
gives me error:
```
ERROR: Could not find a version that satisfies the requirement python==3.6.X (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for python==3.6.X (from -r requirements.txt (line 1))
```

I already tried changing X to 8, but it gives me the same error.

**Comment by RSAStudioGames** [comment]
I was using python 3.8.8 to get tflearn and tensorflow. That seemed to fix the problem for me seeing as tensorflow is only compatible with python up to 3.8.X. I wasnt able to install it with 3.9. That could be your problem.

**Comment by anasselhoud** [comment]
Thank you @RSAStudioGames. I will add this specific version to the requirements file.
