### ISSUE TITLE
I want to make an AI chatbot and moderation bot  and I need a lot of help!

### ISSUE THREAD

**Issue by Sirllamaa** [anasselhoud/AI-MealBot#5]
I am making an AI chatbot and I need your help! I dont evan know where to start!!!

**Comment by anasselhoud** [comment]
Hello @Matthewr7404,

You may want to check my article on this AI chatbot [from here.](https://towardsdatascience.com/how-to-build-your-own-ai-chatbot-on-discord-c6b3468189f4)

It explains the basics of an AI chatbot and how to create it. I recommend you to search for tutorials and articles about natural language processing (NLP).
