### ISSUE TITLE
I want to use the original code

### ISSUE THREAD

**Issue by monibaka** [anasselhoud/AI-MealBot#6]
Hey, I want to use the original code for my own chatbot, I tried contacting you via email, but got no response. Could you share a json file structure that you used? Also did you have already all the possible patterns in it? I'm facing problem in this place. Thanks

**Comment by anasselhoud** [comment]
Hello @monibaka,

Sorry for the late response. I was a bit busy these months.

Please check my article about this AI Chatbot [from here.](https://towardsdatascience.com/how-to-build-your-own-ai-chatbot-on-discord-c6b3468189f4)
It contains in fact the structure of JSON file to use.

Let me know if you need more help.
