### ISSUE TITLE
change requirements.txt

### ISSUE THREAD

**Issue by brewwmannsna** [anasselhoud/AI-MealBot#7]
```
flask>=0.12.3
nltk
tflearn
tensorflow
```
this lets the bot run on almost all the Python versions without causing any problems
tensorflow==1.13.2 wont install on Python 3.8.8
json, pickle are already there and cant be downloaded from PyPi... at least I couldn't find them

**Comment by anasselhoud** [comment]
Thanks, @brewwmannsna for checking that. Would you send a pull request with the changes?

**Comment by anasselhoud** [comment]
Pull requested and merged here: #8 
Thank you!
