### ISSUE TITLE
ntlk not available

### ISSUE THREAD

**Issue by Darthehr** [anasselhoud/AI-MealBot#9]
When I type in
`sudo pip install ntlk`
Then my result is "Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/ntlk/". The ntlk package cannot be found.

**Comment by brewwmannsna** [comment]
its nltk, not ntlk....

**Comment by anasselhoud** [comment]
Hello @Darthehr,
Please use the correct name "nltk" as suggested by @brewwmannsna.
